'use strict';
var COURSE={id:'andesdb-s3-s4',title:'Módulo 2 · Filtrar, resumir y combinar tablas',units:[{id:'s3',label:'Sesión 3',title:'Filtrar mejor y resumir',icon:'📊',deck:'../Presentaciones/M2/sesion-3-filtros-y-agregaciones.html'},{id:'s4',label:'Sesión 4',title:'Uniones de tablas',icon:'🔗',deck:'../Presentaciones/M2/sesion-4-uniones-de-tablas.html'}]};
var STEPS=(window.ANDESDB_S3_STEPS||[]).concat(window.ANDESDB_S4_STEPS||[]);
var SKILLS=['WHERE','ORDER BY','AGG','GROUP BY','HAVING','UNION','JOIN'];
var $=function(id){return document.getElementById(id)};
var db=null,currentIndex=0,hintIndex=0,state=loadState(),lastResult=null;
function loadState(){try{return JSON.parse(localStorage.getItem('andesdb.module.s3s4.v1'))||{xp:0,streak:0,lastDay:null,completed:{},skillXp:{},events:[]};}catch(_){return{xp:0,streak:0,lastDay:null,completed:{},skillXp:{},events:[]};}}
function saveState(){localStorage.setItem('andesdb.module.s3s4.v1',JSON.stringify(state));renderProgress();renderMastery();}
function emit(type,data){state.events=(state.events||[]).slice(-249);state.events.push({type:type,at:new Date().toISOString(),step:STEPS[currentIndex].id,data:data||{}});saveState();}
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function normalize(v){if(v===null)return'__NULL__';if(typeof v==='number')return Number(v.toFixed(8));return String(v);}
function exec(sql){var rs=db.exec(sql);if(!rs.length)return{columns:[],rows:[]};return{columns:rs[0].columns,rows:rs[0].values};}
function canonical(p,order){var rows=p.rows.map(function(r){return r.map(normalize);});if(!order)rows.sort(function(a,b){return JSON.stringify(a).localeCompare(JSON.stringify(b));});return{columns:p.columns.map(function(c){return String(c).toLowerCase();}),rows:rows};}
function same(a,b,order){return JSON.stringify(canonical(a,order))===JSON.stringify(canonical(b,order));}
async function initDb(){var engine=$('engine');engine.textContent='Cargando dvdrental.db real (3,3 MB)…';try{var SQL=await initSqlJs({locateFile:function(file){return'../assets/vendor/sqljs/'+file;}});var res=await fetch('../Presentaciones/M2/base-datos/dvdrental.db?module=s3s4-v1',{cache:'force-cache'});if(!res.ok)throw new Error('HTTP '+res.status);var buf=await res.arrayBuffer();db=new SQL.Database(new Uint8Array(buf));var counts=exec("SELECT (SELECT COUNT(*) FROM film),(SELECT COUNT(*) FROM customer),(SELECT COUNT(*) FROM rental)").rows[0];engine.className='engine ok';engine.textContent='✓ dvdrental real · '+counts[0]+' films · '+counts[1]+' clientes · '+counts[2]+' alquileres · todo local';renderStep(currentIndex,true);}catch(err){engine.className='engine';engine.textContent='No pude cargar dvdrental.db: '+String(err.message||err);setFeedback('Recarga la página. El módulo necesita la base real para validar resultados.','bad');}}
function buildRail(){var rail=$('railUnits');rail.innerHTML='';COURSE.units.forEach(function(u){var sec=document.createElement('section');sec.className='unit';sec.innerHTML='<div class="unit-title"><span>'+u.icon+'</span><div>'+u.label+' · '+esc(u.title)+'</div></div>';var list=document.createElement('div');list.className='step-list';STEPS.forEach(function(s,i){if(s.unit!==u.id)return;var b=document.createElement('button');b.type='button';b.className='step-btn';b.dataset.index=i;b.innerHTML='<span class="step-num">'+(STEPS.filter(function(x,j){return j<=i&&x.unit===u.id;}).length)+'</span><span class="step-copy"><b>'+esc(s.title)+'</b><small>'+esc(s.short)+'</small></span><span class="step-kind">'+kindIcon(s.kind)+'</span>';b.onclick=function(){go(i);};list.appendChild(b);});sec.appendChild(list);rail.appendChild(sec);});}
function kindIcon(k){return k==='lab'?'⌨':k==='quiz'?'?':'◎';}
function renderStep(index,fromDb){currentIndex=index;hintIndex=0;lastResult=null;var s=STEPS[index],u=COURSE.units.find(function(x){return x.id===s.unit;});document.querySelectorAll('.step-btn').forEach(function(b){var i=Number(b.dataset.index);b.classList.toggle('on',i===index);b.classList.toggle('done',!!state.completed[STEPS[i].id]);});$('moduleTitle').textContent=u.label+' · '+u.title;$('stepEy').textContent=u.label+' · '+kindLabel(s.kind)+' · '+(index+1)+'/'+STEPS.length;$('stepTitle').textContent=s.title;$('stepLead').textContent=s.lead;$('sourceLink').href=u.deck;$('sourceLink').textContent='Abrir la presentación fuente ↗';$('stepMeta').innerHTML='<span class="pill">≈ '+s.minutes+' min</span><span class="pill">+'+s.xp+' XP</span><span class="pill">'+s.skills.join(' · ')+'</span>';$('lessonContent').innerHTML=s.body+'<div id="visual" class="visual"></div><div id="quizArea"></div>';renderVisual(s.visual,s);if(s.quiz)renderQuiz(s);renderStudio(s);$('prevBtn').disabled=index===0;$('nextBtn').disabled=index===STEPS.length-1;$('completeLearn').style.display=s.kind==='learn'?'inline-block':'none';$('completeLearn').textContent=state.completed[s.id]?'✓ Comprendido':'Marcar como comprendido';if(innerWidth<=760)showMobile('learn');renderProgress();renderMastery();if(!fromDb)emit('step_opened',{kind:s.kind,unit:s.unit});}
function kindLabel(k){return k==='lab'?'Laboratorio':k==='quiz'?'Comprobación':'Microlección';}
