function run(){if(!db){setFeedback('La base todavía se está cargando. Espera a que diga “dvdrental real”.','warn');return;}var s=STEPS[currentIndex],sql=$('sqlEditor').value,pf=preflight(sql);resetChecks();if(pf){setFeedback('🧭 '+pf,'warn');return;}var t=performance.now();try{var payload=exec(sql);lastResult=payload;renderResult(payload);$('queryTime').textContent=(performance.now()-t).toFixed(1)+' ms';if(!s.lab){setFeedback('Consulta ejecutada en la base real. Usa el resultado para razonar sobre la microlección.','good');emit('sql_executed',{ok:true,free:true,rows:payload.rows.length});return;}var expected=exec(s.lab.expected),order=!!s.lab.orderMatters||/ORDER\s+BY/i.test(s.lab.expected),colsOk=JSON.stringify(payload.columns.map(lower))===JSON.stringify(expected.columns.map(lower)),rowsOk=payload.rows.length===expected.rows.length,valuesOk=same(payload,expected,order),conceptOk=checkRequired(sql,s.lab.required||[]);mark('ckCols',colsOk);mark('ckRows',rowsOk);mark('ckValues',valuesOk);mark('ckConcept',conceptOk);if(valuesOk&&conceptOk){setFeedback('✅ Correcto. Produjiste la respuesta esperada con el concepto que esta misión quería practicar.','good');complete(s);}else if(valuesOk&&!conceptOk){setFeedback('El resultado coincide, pero intenta resolverlo usando: '+s.lab.required.join(', ')+'.','warn');}else{var msg=[];if(!colsOk)msg.push('revisa columnas');if(!rowsOk)msg.push('esperábamos '+expected.rows.length+' fila(s) y obtuviste '+payload.rows.length);if(rowsOk&&!valuesOk)msg.push('revisa valores u orden');setFeedback('Todavía no coincide: '+(msg.join('; ')||'revisa filtros, relaciones o nivel de agregación')+'.','warn');}emit('sql_executed',{ok:true,rows:payload.rows.length,correct:valuesOk&&conceptOk});}catch(err){$('result').innerHTML='';$('queryTime').textContent='';setFeedback('🔴 '+translateError(err),'bad');emit('sql_executed',{ok:false,error:String(err&&err.message||err).slice(0,180)});}}
function lower(x){return String(x).toLowerCase();}
function checkRequired(sql,req){var u=' '+sql.toUpperCase().replace(/\s+/g,' ')+' ';return req.every(function(r){return u.indexOf(String(r).toUpperCase())>=0;});}
function mark(id,ok){var e=$(id);e.className='check '+(ok?'ok':'bad');}
function resetChecks(){['ckCols','ckRows','ckValues','ckConcept'].forEach(function(id){var e=$(id);if(e)e.className='check';});}
function renderResult(p){var box=$('result');if(!p.columns.length){box.innerHTML='<div class="muted">La sentencia se ejecutó, pero no devolvió una tabla.</div>';return;}var limit=200,rows=p.rows.slice(0,limit),html='<table><thead><tr>'+p.columns.map(function(c){return'<th>'+esc(c)+'</th>';}).join('')+'</tr></thead><tbody>';html+=rows.map(function(r){return'<tr>'+r.map(function(v){return'<td>'+(v===null?'<span style="color:#ffbd78">NULL</span>':esc(v))+'</td>';}).join('')+'</tr>';}).join('')+'</tbody></table>';if(p.rows.length>limit)html+='<div class="muted" style="padding:7px">Mostrando '+limit+' de '+p.rows.length+' filas.</div>';box.innerHTML=html;}
function setFeedback(text,type){var f=$('feedback');f.className='feedback '+(type||'');f.textContent=text;}
function complete(s){if(state.completed[s.id]){renderProgress();return;}state.completed[s.id]={at:new Date().toISOString(),xp:s.xp};state.xp+=s.xp;(s.skills||[]).forEach(function(sk){state.skillXp[sk]=(state.skillXp[sk]||0)+s.xp;});touchStreak();saveState();document.querySelectorAll('.step-btn').forEach(function(b){var i=Number(b.dataset.index);b.classList.toggle('done',!!state.completed[STEPS[i].id]);});if(s.kind==='learn')$('completeLearn').textContent='✓ Comprendido';emit('step_completed',{xp:s.xp});}
function touchStreak(){var day=new Date().toISOString().slice(0,10);if(state.lastDay===day)return;var y=new Date(Date.now()-86400000).toISOString().slice(0,10);state.streak=state.lastDay===y?(state.streak||0)+1:1;state.lastDay=day;}
function renderProgress(){var done=Object.keys(state.completed||{}).length,pct=Math.round(done/STEPS.length*100);$('topProgress').style.width=pct+'%';$('xp').textContent=state.xp||0;$('streak').textContent=state.streak||0;$('moduleProgress').textContent=done+'/'+STEPS.length+' pasos';}
function renderMastery(){var box=$('mastery');box.innerHTML='';SKILLS.forEach(function(sk){var earned=state.skillXp[sk]||0,possible=STEPS.filter(function(s){return(s.skills||[]).indexOf(sk)>=0;}).reduce(function(a,s){return a+s.xp;},0)||1,pct=Math.min(100,Math.round(earned/possible*100));var d=document.createElement('div');d.className='skill';d.innerHTML='<label><span>'+esc(sk)+'</span><span>'+pct+'%</span></label><div class="track"><i style="width:'+pct+'%"></i></div>';box.appendChild(d);});}
function showHint(){var s=STEPS[currentIndex];if(!s.lab){setFeedback('Esta etapa es conceptual. Usa el playground para experimentar.','warn');return;}var hs=s.lab.hints||[],i=Math.min(hintIndex,hs.length-1);$('hintBox').hidden=false;$('hintBox').innerHTML='<b>Pista '+(i+1)+'/'+hs.length+'</b><br>'+esc(hs[i]);if(hintIndex<hs.length-1)hintIndex++;emit('hint_requested',{level:i+1});}
function explainSql(){var sql=$('sqlEditor').value.trim();$('hintBox').hidden=false;if(!sql){$('hintBox').textContent='Escribe SQL y luego usa “Explícame”.';return;}var pairs=[['FROM','parte de una fuente de filas'],['JOIN','combina otra tabla'],['WHERE','filtra filas antes de agrupar'],['GROUP BY','forma grupos'],['HAVING','filtra grupos'],['SELECT','define la salida'],['ORDER BY','ordena la respuesta'],['LIMIT','reduce filas mostradas'],['UNION ALL','apila conservando repetidos'],['UNION','apila eliminando repetidos']];var found=[];pairs.forEach(function(p){if(new RegExp('\\b'+p[0].replace(' ','\\s+')+'\\b','i').test(sql))found.push('<b>'+p[0]+'</b>: '+p[1]);});$('hintBox').innerHTML=found.length?found.join('<br>'):'Todavía no reconozco suficientes cláusulas.';emit('query_explained',{clauses:found.length});}
function showData(){if(!db)return;var s=STEPS[currentIndex],q='SELECT * FROM film LIMIT 8;';if(s.id==='s4-bridge')q='SELECT * FROM film_actor LIMIT 8;';if(s.id==='s4-keys')q='SELECT customer_id,first_name,address_id FROM customer LIMIT 8;';if(s.id==='s3-boss'||s.id==='s3-order')q='SELECT * FROM payment LIMIT 8;';$('sqlEditor').value=q;run();}
function insertToken(t){var e=$('sqlEditor'),a=e.selectionStart,b=e.selectionEnd;e.value=e.value.slice(0,a)+t+e.value.slice(b);e.focus();e.selectionStart=e.selectionEnd=a+t.length;}
function buildChips(){var box=$('chips');['SELECT ','FROM ','WHERE ','BETWEEN ','IN ','LIKE ','GROUP BY ','HAVING ','JOIN ','LEFT JOIN ','ON ','UNION ALL ','COUNT(*) ','ORDER BY '].forEach(function(t){var b=document.createElement('button');b.type='button';b.textContent=t.trim();b.onclick=function(){insertToken(t);};box.appendChild(b);});}
function go(i){if(i<0||i>=STEPS.length)return;renderStep(i);window.scrollTo({top:0,behavior:'smooth'});}
function showMobile(which){var learn=which==='learn';$('mainPanel').classList.toggle('mobile-off',!learn);$('studio').classList.toggle('mobile-on',!learn);$('mobileLearn').classList.toggle('on',learn);$('mobilePractice').classList.toggle('on',!learn);}
function bind(){$('prevBtn').onclick=function(){go(currentIndex-1);};$('nextBtn').onclick=function(){go(currentIndex+1);};$('completeLearn').onclick=function(){complete(STEPS[currentIndex]);};$('runBtn').onclick=run;$('dockRun').onclick=function(){showMobile('practice');run();};$('hintBtn').onclick=showHint;$('dockHint').onclick=function(){showMobile('practice');showHint();};$('explainBtn').onclick=explainSql;$('dataBtn').onclick=showData;$('dockPrev').onclick=function(){go(currentIndex-1);};$('dockNext').onclick=function(){go(currentIndex+1);};$('mobileLearn').onclick=function(){showMobile('learn');};$('mobilePractice').onclick=function(){showMobile('practice');};$('sqlEditor').addEventListener('keydown',function(e){if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();run();}if(e.key==='Tab'){e.preventDefault();insertToken('  ');}});}
buildRail();buildChips();bind();renderStep(0);initDb();
