# -*- coding: utf-8 -*-
"""Sincroniza la Sesión 15 con su evaluador automático.

Mantiene idénticas las presentaciones pública/revisión, alinea manifiestos y
learning-plan, y elimina la vieja capa Núcleo/Reto que mostraba instrucciones
paralelas. Es idempotente y se ejecuta antes de generar los índices.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

PRESENTATION = r'''<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="description" content="Sesión 15 · Desafío final con evaluación automática"><title>Sesión 15 · Demuestra que funciona</title><link rel="stylesheet" href="/ANDESDB/tools/tema-v2.css"><style>
.ctlbar{position:fixed;left:50%;bottom:.65rem;transform:translateX(-50%);z-index:70;display:flex;gap:.35rem;align-items:center;background:#111d;padding:.3rem .45rem;border-radius:999px}.ctlbar button,.ctlbar a{border:0;border-radius:999px;background:#fff;color:#171717;padding:.38rem .62rem;font-weight:800;text-decoration:none;cursor:pointer}.ctlbar span{color:#fff;min-width:5em;text-align:center;font-weight:800}.links a{display:block;margin:.42em 0;color:var(--b);font-weight:800;overflow-wrap:anywhere}.score4{display:grid;grid-template-columns:repeat(4,1fr);gap:.7em;margin:1em 0}.score4 article{background:#fff;border:1px solid #dce4ea;border-radius:15px;padding:.85em;box-shadow:var(--sh);border-top:5px solid var(--y)}.score4 article:nth-child(even){background:var(--bl);border-top-color:var(--b)}.score4 b{display:block;font-size:1.5em}.pipeline{display:grid;grid-template-columns:repeat(4,1fr);gap:.7em;margin:1em 0}.pipeline article{border-radius:14px;background:var(--s);padding:.85em;border-left:5px solid var(--y)}.pipeline b{display:block;margin-bottom:.3em}.testlist{display:grid;grid-template-columns:repeat(5,1fr);gap:.55em;margin:.8em 0}.testlist article{background:#fff;border:1px solid #dde4e9;border-radius:12px;padding:.7em;min-height:8em}.testlist b{display:block;color:var(--b);margin-bottom:.3em}.variant{display:grid;grid-template-columns:repeat(3,1fr);gap:.7em;margin:.8em 0}.variant article{border-radius:14px;padding:.85em;background:#fff;border:1px solid #dce4ea}.variant article:nth-child(2){background:#fff9df}.variant article:nth-child(3){background:#eef7ff}.auto{background:#eaf8ef;border-left:5px solid var(--g);border-radius:12px;padding:.75em .9em;margin:.7em 0}.anti{background:#fff1e8;border-left:5px solid var(--o);border-radius:12px;padding:.75em .9em;margin:.7em 0}.cta-auto{display:inline-flex;align-items:center;gap:.4em;background:#17202a;color:#fff!important;border-radius:999px;padding:.65em 1em;text-decoration:none;font-weight:900!important;margin:.35em 0}.cta-auto:after{content:'→'}
@media(max-width:760px),(max-aspect-ratio:1/1){.score4,.pipeline,.testlist,.variant{grid-template-columns:1fr}.testlist article{min-height:auto}}
</style></head><body><main class="stage">
<section class="slide dark active" data-title="Portada"><div class="ey">Sesión 15 · desafío integrador</div><h1>No entregues una solución que <span class="accent">parezca correcta</span></h1><p class="lead">Demuestra que entiende el problema, protege reglas y sigue respondiendo cuando cambian los datos.</p><div class="links"><a class="cta-auto" href="/ANDESDB/evaluador-s15.html" target="_blank">Abrir evaluador automático</a></div><div class="brand"><span>ANDESDB · Sesión 15</span><span>Decidir → construir → probar → corregir</span></div></section>
<section class="slide dense" data-title="Evaluación"><div class="ey">Contrato de evaluación</div><h2>La evaluación ocurre dentro de una sola herramienta</h2><div class="score4"><article><b>20</b><span>Grano y lectura de fuentes</span></article><article><b>25</b><span>DDL e integridad</span></article><article><b>35</b><span>SQL y validación</span></article><article><b>20</b><span>Arquitectura y adaptabilidad</span></article></div><div class="auto"><b>Automática de principio a fin.</b> El estudiante recibe puntaje, desglose y explicación de qué revisar. Puede corregir solo lo que falló y volver a intentar.</div><div class="brand"><span>100 puntos</span><span>Retroalimentación inmediata</span></div></section>
<section class="slide dense" data-title="Cómo funciona"><div class="ey">Qué hace el evaluador</div><h2>El código se prueba; no se califica por apariencia</h2><div class="pipeline"><article><b>1 · Decide</b><p>Responde preguntas deterministas sobre grano y requisitos.</p></article><article><b>2 · Ejecuta</b><p>SQL.js corre DDL y consultas dentro del navegador.</p></article><article><b>3 · Cambia datos</b><p>El evaluador añade casos, eventos y un estado nuevo para probar robustez.</p></article><article><b>4 · Registra</b><p>El intento final guarda nota y feedback en el LMS si hay sesión iniciada.</p></article></div><div class="checkpoint"><b>Importante:</b> no se evalúa que el SQL sea idéntico al del profesor. Se evalúa que produzca el comportamiento esperado.</div><div class="brand"><span>Motor local</span><span>Variaciones + LMS</span></div></section>
<section class="slide dense" data-title="Caso"><div class="ey">Caso nuevo</div><h2>Atención de incidentes urbanos</h2><p class="lead">La ciudad recibe reportes de alumbrado, ruido, huecos, basuras y semáforos. Un caso tiene estado actual, acumula eventos y puede tener evidencias de formas diferentes.</p><div class="g3"><div class="card"><h3>Operación</h3><p>Casos, estado actual y reglas que deben permanecer consistentes.</p></div><div class="card blue"><h3>Historia</h3><p>Cambios de estado y agentes aparecen como eventos 1:N.</p></div><div class="card"><h3>Evidencia</h3><p>Fotos, videos y comentarios viven en arreglos de tamaño variable.</p></div></div><div class="brand"><span>Caso final</span><span>Problema nuevo, conceptos conocidos</span></div></section>
<section class="slide dense" data-title="Fuentes"><div class="ey">Puerta 1</div><h2>Tres fuentes, tres preguntas de grano</h2><div class="links"><a href="/ANDESDB/Plantillas/proyecto-final/Datos/casos.csv" download>📊 casos.csv · snapshot actual</a><a href="/ANDESDB/Plantillas/proyecto-final/Datos/eventos.csv" download>📊 eventos.csv · historial</a><a href="/ANDESDB/Plantillas/proyecto-final/Datos/evidencias.json" download>📄 evidencias.json · documentos anidados</a></div><div class="g3"><div class="card"><h3>casos</h3><p>¿Qué representa una fila?</p></div><div class="card blue"><h3>eventos</h3><p>¿Qué representa una fila y cuántas puede tener un caso?</p></div><div class="card"><h3>evidencias</h3><p>¿Qué representa el documento y qué representa el arreglo?</p></div></div><div class="checkpoint">El evaluador empieza aquí. Si el grano está mal, el JOIN y los indicadores se vuelven frágiles después.</div><div class="brand"><span>20 puntos</span><span>Significado antes de SQL</span></div></section>
<section class="slide dense" data-title="Checkpoint 1"><div class="ey">Trabaja en la herramienta</div><h2>Abre el evaluador y completa la primera sección</h2><div class="links"><a class="cta-auto" href="/ANDESDB/evaluador-s15.html#secConcept" target="_blank">Ir a Grano y fuentes</a></div><div class="g2"><div class="card"><h3>Hazlo individualmente</h3><p>Las respuestas son cerradas porque aquí queremos una evaluación reproducible, no discutir una redacción ambigua.</p></div><div class="card blue"><h3>Usa la retroalimentación</h3><p>Si falla una decisión, corrígela antes de construir. El borrador se guarda automáticamente en el navegador.</p></div></div><div class="brand"><span>Checkpoint</span><span>Decide → comprueba → continúa</span></div></section>
<section class="slide dense" data-title="Contrato DDL"><div class="ey">Puerta 2 · modelo</div><h2>Protege solo reglas que sí están confirmadas</h2><div class="g2"><div class="card"><h3>Debe proteger</h3><ul class="checks"><li>identidad de casos y eventos</li><li>evento pertenece a un caso</li><li>campos requeridos</li><li>minutos no negativos</li></ul></div><div class="card blue"><h3>No debe inventar</h3><p>Que hoy veamos tres estados no prueba que sean el universo completo. El evaluador introduce <code>Escalado</code> para comprobar adaptabilidad.</p></div></div><div class="checkpoint"><b>La prueba importante:</b> el modelo debe rechazar lo inválido sin rechazar una evolución legítima del negocio.</div><div class="brand"><span>DDL</span><span>Integridad ≠ rigidez inventada</span></div></section>
<section class="slide dense" data-title="Pruebas DDL"><div class="ey">25 puntos ejecutables</div><h2>Cinco pruebas sustituyen la revisión manual del esquema</h2><div class="testlist"><article><b>D1</b><p>PK: duplicados deben fallar.</p></article><article><b>D2</b><p>FK: un evento huérfano debe fallar.</p></article><article><b>D3</b><p>NOT NULL: datos requeridos no pueden desaparecer.</p></article><article><b>D4</b><p>CHECK: minutos negativos deben fallar.</p></article><article><b>D5</b><p>Evolución: el nuevo estado <code>Escalado</code> debe poder entrar.</p></article></div><div class="links"><a class="cta-auto" href="/ANDESDB/evaluador-s15.html#secDDL" target="_blank">Escribir y probar DDL</a></div><div class="brand"><span>25 puntos</span><span>El esquema demuestra su comportamiento</span></div></section>
<section class="slide yellow" data-title="Pausa"><div class="ey">Pausa</div><h2>Pausa · 15 minutos</h2><p class="lead">Al volver: cuatro consultas que deben sobrevivir cuando el evaluador cambia los datos.</p><div class="brand"><span>Pausa</span><span>Luego: SQL + variaciones</span></div></section>
<section class="slide dense" data-title="Consultas 1 y 2"><div class="ey">Puerta 3 · SQL</div><h2>Primero responde; después demuestra que no dependías de los números originales</h2><div class="g2"><div class="card"><h3>Q1 · prioridad Alta por barrio</h3><p>Una agregación cuyo resultado cambia cuando aparece un caso Alta nuevo.</p></div><div class="card blue"><h3>Q2 · estado actual vs último evento</h3><p>Obliga a reconocer que <code>MAX(estado)</code> no significa “último”. La fecha define la secuencia.</p></div></div><div class="anti"><b>No hardcodees.</b> Una consulta que devuelve los números correctos sobre los doce casos pero falla al agregar una fila no demuestra comprensión.</div><div class="brand"><span>SQL</span><span>Resultado + generalización</span></div></section>
<section class="slide dense" data-title="Consultas 3 y 4"><div class="ey">Control de historia y grano</div><h2>Dos consultas atacan los errores más costosos del curso</h2><div class="g2"><div class="card"><h3>Q3 · minutos hasta cierre</h3><p>Debe identificar cuáles casos terminan cerrados y acumular sus eventos, incluso si aparece un evento intermedio adicional.</p></div><div class="card blue"><h3>Q4 · JOIN sin inflación</h3><p>Debe contar casos y eventos a sus respectivos granos. Tener dos eventos no puede convertir un caso en dos casos.</p></div></div><div class="checkpoint">El evaluador compara resultados, no busca una sintaxis específica. CTE, subconsulta o ventana pueden ser válidas si el comportamiento es correcto.</div><div class="links"><a class="cta-auto" href="/ANDESDB/evaluador-s15.html#secQueries" target="_blank">Ejecutar las cuatro consultas</a></div><div class="brand"><span>35 puntos</span><span>SQL probado, no SQL decorativo</span></div></section>
<section class="slide dense" data-title="Variaciones"><div class="ey">Antihardcoding pedagógico</div><h2>Las mismas consultas se ejecutan sobre tres mundos</h2><div class="variant"><article><h3>Base</h3><p>Los datos que descargaste.</p></article><article><h3>Variación A</h3><p>Aparece un caso Alta en Bosa y eventos adicionales.</p></article><article><h3>Variación B</h3><p>Otro caso cierra y aparece el estado <code>Escalado</code>.</p></article></div><div class="auto"><b>Retroalimentación útil:</b> si pasa los datos visibles pero falla una variación, el sistema lo dice explícitamente. Eso distingue “obtuve el número” de “construí una consulta general”.</div><div class="brand"><span>Pruebas variables</span><span>Menos memorización, más transferencia</span></div></section>
<section class="slide dense" data-title="Decisiones"><div class="ey">Puerta 4 · arquitectura</div><h2>La última parte evalúa decisiones con requisitos explícitos</h2><div class="score4"><article><b>A1</b><span>snapshot + historia</span></article><article><b>A2</b><span>evidencia variable</span></article><article><b>A3</b><span>OLTP vs analítica</span></article><article><b>A4</b><span>evolución del dominio</span></article></div><p class="lead">No se pregunta “¿SQL o NoSQL cuál es mejor?”. Cada escenario fija el patrón de acceso o la restricción que hace defendible una elección.</p><div class="links"><a class="cta-auto" href="/ANDESDB/evaluador-s15.html#secArch" target="_blank">Resolver decisiones</a></div><div class="brand"><span>20 puntos</span><span>Requisito → decisión</span></div></section>
<section class="slide dense" data-title="Intento final"><div class="ey">Evaluación y feedback</div><h2>Un intento no es una foto final: es un ciclo de corrección</h2><div class="pipeline"><article><b>Ejecuta todo</b><p>DDL, SQL, variaciones y decisiones.</p></article><article><b>Recibe desglose</b><p>20 / 25 / 35 / 20 por dimensión.</p></article><article><b>Lee prioridades</b><p>Cada fallo explica qué concepto o comportamiento revisar.</p></article><article><b>Reintenta</b><p>Corrige solo lo necesario; el LMS conserva cada intento.</p></article></div><div class="links"><a class="cta-auto" href="/ANDESDB/evaluador-s15.html" target="_blank">Evaluar y registrar intento</a></div><div class="checkpoint">Si no has iniciado sesión en el LMS, el evaluador funciona en modo local pero te avisará que la nota todavía no quedó registrada.</div><div class="brand"><span>Feedback automático</span><span>Corregir forma parte de la evaluación</span></div></section>
<section class="slide dark" data-title="Cierre"><div class="ey">Cierre S15</div><h2>La evidencia final no es un archivo: es una solución que <span class="accent">sobrevive pruebas</span></h2><div class="g3"><div class="card"><h3>Entendiste</h3><p>si controlas el grano.</p></div><div class="card blue"><h3>Construiste</h3><p>si el esquema protege reglas reales.</p></div><div class="card"><h3>Transferiste</h3><p>si SQL y decisiones siguen funcionando ante cambios.</p></div></div><p class="lead">En S16 el foco cambia: leer el patrón de tus resultados y transferir lo aprendido al mapa DP-900.</p><div class="brand"><span>Sesión 15</span><span>De plausible a comprobable</span></div></section>
</main><nav class="ctlbar" aria-label="Navegación"><button id="prev" aria-label="Anterior">←</button><span id="count">1 / 15</span><button id="next" aria-label="Siguiente">→</button><a href="/ANDESDB/evaluador-s15.html" target="_blank" aria-label="Evaluador">✓</a></nav>
<script>(()=>{const s=[...document.querySelectorAll('.slide')];let i=0,c=document.getElementById('count');function show(n){s[i]?.classList.remove('active');i=(n+s.length)%s.length;s[i].classList.add('active');c.textContent=`${i+1} / ${s.length}`;history.replaceState(null,'',`#${i+1}`)}document.getElementById('prev').onclick=()=>show(i-1);document.getElementById('next').onclick=()=>show(i+1);addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;if(e.key==='ArrowRight'||e.key==='PageDown')show(i+1);if(e.key==='ArrowLeft'||e.key==='PageUp')show(i-1);if(e.key.toLowerCase()==='f')document.documentElement.requestFullscreen?.()});const h=Number(location.hash.slice(1));if(h>=1&&h<=s.length)show(h-1)})();</script>
<script src="/ANDESDB/assets/learning/presentation-timer.js?v=20260916-auto1"></script><script src="/ANDESDB/assets/analytics-config.js?v=20260912a"></script><script src="/ANDESDB/assets/analytics.js?v=20260912a"></script></body></html>
'''

CAPSTONE = r'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="ANDESDB · Sesión 15 automática"><title>ANDESDB · Sesión 15</title><style>
:root{--ink:#17202a;--muted:#667085;--line:#e4e7ec;--bg:#f7f8fa;--dark:#101828;--yellow:#ffd600;--blue:#175cd3;--green:#16794b}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;line-height:1.5}.bar{background:var(--dark);color:#fff}.barin,.wrap{width:min(980px,94vw);margin:auto}.barin{min-height:58px;display:flex;align-items:center;gap:10px}.brand{font-weight:900;color:#fff;text-decoration:none}.hero{background:linear-gradient(145deg,#132238,#1d3e5d);color:#fff;padding:34px 0}.ey{font-size:.7rem;letter-spacing:.12em;text-transform:uppercase;color:var(--yellow);font-weight:900}.hero h1{font-size:clamp(2rem,7vw,3.7rem);line-height:1;margin:.35rem 0 .65rem;max-width:16ch}.hero p{max-width:76ch;color:#d0d5dd}.wrap{padding:20px 0 70px}.grid{display:grid;grid-template-columns:1.1fr .9fr;gap:14px}.card{background:#fff;border:1px solid var(--line);border-radius:16px;padding:16px;margin-bottom:14px;box-shadow:0 8px 26px #1018280a}.card h2{font-size:1.15rem;margin:.05rem 0 .55rem}.steps{display:grid;gap:8px}.step{border:1px solid #e4e7ec;border-radius:11px;padding:10px}.step b{display:block}.rubric{display:grid;gap:7px}.criterion{display:grid;grid-template-columns:1fr auto;gap:8px;padding:9px 0;border-bottom:1px solid #eef1f4}.criterion:last-child{border:0}.criterion p{grid-column:1/-1;margin:0;color:var(--muted);font-size:.78rem}.pts{font-weight:900;color:var(--blue)}.resources{display:grid;gap:7px}.resources a{display:block;border:1px solid #e1e6ec;border-radius:10px;padding:10px;text-decoration:none;color:var(--ink);font-weight:800}.resources small{display:block;color:var(--muted);font-weight:500}.cta{background:#fff8c8;border:1px solid #ead56d;border-radius:16px;padding:16px}.btn{display:flex;justify-content:center;border-radius:10px;background:#101828;color:#fff;padding:12px;text-decoration:none;font-weight:900;margin-top:8px}.note{font-size:.8rem;color:var(--muted);border-left:4px solid var(--yellow);padding-left:9px}.auto{background:#ecfdf3;border-left:4px solid var(--green);border-radius:10px;padding:10px;margin-top:10px}@media(max-width:760px){.grid{grid-template-columns:1fr}}</style></head><body>
<header class="bar"><div class="barin"><a class="brand" href="/ANDESDB/">ANDESDB</a></div></header><section class="hero"><div class="barin"><div><div class="ey">Sesión 15 · evaluación automática</div><h1>Demuestra que funciona</h1><p>El desafío final ya no se entrega como un paquete de archivos para corrección manual. Una herramienta ejecuta tu modelo y tus consultas, cambia los datos, puntúa cuatro dimensiones y registra cada intento en el LMS.</p></div></div></section>
<main class="wrap"><div class="grid"><div><section class="cta"><div class="ey" style="color:#7a6500">Herramienta principal</div><h2>Evaluador automático S15</h2><p>Trabaja aquí durante la sesión. El borrador se guarda en el navegador y el intento final recibe retroalimentación inmediata.</p><a class="btn" href="/ANDESDB/evaluador-s15.html">Abrir evaluador automático</a><a class="btn" href="/ANDESDB/Presentaciones/M6/sesion-15-desafio-final.html">Abrir presentación</a></section><section class="card"><h2>Qué ocurre al evaluar</h2><div class="steps"><div class="step"><b>1 · Comprueba el grano</b><span>Decisiones cerradas evitan subjetividad de redacción.</span></div><div class="step"><b>2 · Ejecuta tu DDL</b><span>PK, FK, NULL, valores negativos y evolución del estado se prueban de verdad.</span></div><div class="step"><b>3 · Ejecuta cuatro consultas</b><span>Cada consulta se repite sobre datos base y variaciones automáticas.</span></div><div class="step"><b>4 · Devuelve feedback</b><span>Obtienes desglose, errores concretos y puedes volver a intentar.</span></div><div class="step"><b>5 · Guarda en el LMS</b><span>Con sesión iniciada, nota, código, desglose e intento quedan registrados.</span></div></div><div class="auto"><b>La corrección es parte del proceso.</b> No se penaliza necesitar un segundo intento: el historial permite ver qué cambió.</div></section></div><aside><section class="card"><h2>Rúbrica automática</h2><div class="rubric"><div class="criterion"><b>Grano y lectura de fuentes</b><span class="pts">20</span><p>Cinco decisiones deterministas sobre significado, cardinalidad y JOIN.</p></div><div class="criterion"><b>DDL e integridad</b><span class="pts">25</span><p>Cinco pruebas ejecutadas sobre el esquema.</p></div><div class="criterion"><b>SQL y validación</b><span class="pts">35</span><p>Cuatro consultas ejecutadas sobre datos visibles y variantes.</p></div><div class="criterion"><b>Arquitectura y adaptabilidad</b><span class="pts">20</span><p>Cuatro decisiones dadas restricciones explícitas.</p></div></div></section><section class="card"><h2>Datos de trabajo</h2><div class="resources"><a href="/ANDESDB/Plantillas/proyecto-final/Datos/casos.csv" download>📊 casos.csv<small>Snapshot operacional.</small></a><a href="/ANDESDB/Plantillas/proyecto-final/Datos/eventos.csv" download>📊 eventos.csv<small>Historial 1:N.</small></a><a href="/ANDESDB/Plantillas/proyecto-final/Datos/evidencias.json" download>📄 evidencias.json<small>Documentos con arreglos.</small></a><a href="/ANDESDB/Plantillas/proyecto-final/criterios.md">✅ Contrato de evaluación<small>Qué se prueba y por qué.</small></a></div></section><p class="note">El SQL se ejecuta localmente con SQL.js. El LMS recibe el resumen del intento final, no cada tecla ni cada ejecución formativa.</p></aside></div></main></body></html>
'''

CRITERIA = '''# Sesión 15 · Contrato de evaluación automática\n\nLa evaluación se realiza en `evaluador-s15.html`. No se califica un paquete de archivos manualmente. Cada estudiante trabaja sobre las mismas fuentes, recibe retroalimentación inmediata y puede corregir antes de registrar otro intento.\n\n## Rúbrica · 100 puntos\n\n- **20 · Grano y lectura de fuentes.** Cinco decisiones deterministas sobre qué representa cada fuente, cardinalidad y riesgo de multiplicar filas.\n- **25 · DDL e integridad.** Cinco pruebas ejecutadas sobre el esquema: PK, FK, obligatoriedad, minutos no negativos y capacidad de aceptar un estado nuevo no prohibido por el negocio.\n- **35 · SQL y validación.** Cuatro consultas se ejecutan sobre los datos visibles y sobre variaciones automáticas. Se comparan resultados, no una sintaxis específica.\n- **20 · Arquitectura y adaptabilidad.** Cuatro escenarios cerrados obligan a decidir a partir de requisitos de acceso, consistencia, carga y evolución.\n\n## Fuentes\n\n- `casos.csv`: una fila = un caso reportado y su estado actual.\n- `eventos.csv`: una fila = un evento/cambio asociado a un caso.\n- `evidencias.json`: un documento = un caso con un arreglo de evidencias.\n\nLos datos base contienen 12 casos, 24 eventos y 4 documentos de evidencias. Esos números sirven para explorar, pero **no bastan para aprobar las consultas**: el evaluador agrega datos en copias internas.\n\n## Contrato del DDL\n\nLa herramienta solicita dos tablas con nombres y columnas mínimas conocidas:\n\n- `caso(caso_id INTEGER, fecha_creacion TEXT, tipo TEXT, prioridad TEXT, estado TEXT, barrio TEXT)`\n- `evento(evento_id TEXT, caso_id INTEGER, fecha_evento TEXT, estado TEXT, minutos_desde_anterior INTEGER)`\n\nReglas confirmadas: identificadores únicos, evento asociado a un caso existente, campos listados obligatorios y minutos no negativos. **No está confirmado** que `Abierto`, `En_proceso` y `Cerrado` sean la lista completa de estados; por eso el evaluador prueba el estado nuevo `Escalado`.\n\n## Consultas evaluadas\n\nEl evaluador expone `casos_src` y `eventos_src` y pide:\n\n1. prioridad Alta por barrio → `barrio, casos_alta`;\n2. estado actual frente al último evento → `caso_id, estado_actual, ultimo_estado`;\n3. minutos acumulados para casos cuyo último evento es Cerrado → `caso_id, minutos_hasta_cierre`;\n4. control de grano tras unir casos y eventos → `total_casos, total_eventos, casos_alta`.\n\nCada consulta debe seguir siendo correcta cuando aparecen casos/eventos adicionales. No se debe usar un resultado fijo ni ocultar un problema de grano con un número hardcodeado.\n\n## Retroalimentación e intentos\n\nEl botón final vuelve a ejecutar todas las pruebas, entrega puntaje por dimensión y explica cada criterio fallido. Si el estudiante está autenticado en ANDESDB, el intento se registra automáticamente en el LMS con código, desglose y feedback. Puede corregir y volver a intentar; cada intento queda en el historial.\n'''

README = '''# Sesión 15 · Atención de incidentes urbanos\n\nLa herramienta principal es el **evaluador automático**: [`/ANDESDB/evaluador-s15.html`](/ANDESDB/evaluador-s15.html).\n\nNo necesitas preparar seis archivos para que el profesor los revise manualmente. Durante la sesión:\n\n1. identifica el grano de `casos.csv`, `eventos.csv` y `evidencias.json`;\n2. escribe un DDL mínimo que proteja reglas confirmadas;\n3. ejecuta las cuatro consultas pedidas;\n4. responde escenarios de arquitectura;\n5. usa la retroalimentación automática para corregir;\n6. registra el intento final en el LMS.\n\nLos archivos de esta carpeta siguen disponibles como apoyo y para explorar los datos, pero **la evidencia evaluada vive en el intento automático**. Consulta `criterios.md` para conocer las pruebas y la rúbrica.\n'''


def dump(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def update_course(path: Path) -> None:
    course = json.loads(path.read_text(encoding="utf-8"))
    course["metodologia"]["diferenciacionTecnicaSesiones"] = [11, 12, 13, 14]
    m6 = next(m for m in course["modulos"] if m["n"] == 6)
    m6["desc"] = "Integrar el recorrido en un caso nuevo mediante una evaluación automática que ejecuta, prueba, retroalimenta y registra intentos; cerrar después con transferencia hacia DP-900."
    s15 = next(s for s in m6["sesiones"] if s["n"] == 15)
    s15.pop("trabajoAutonomoMin", None)
    s15.update({
        "modo": "evaluacion_automatica_guiada",
        "titulo": "Desafío final · evaluación automática",
        "desc": "Caso de incidentes urbanos evaluado automáticamente: grano, DDL e integridad, cuatro consultas sometidas a variaciones de datos y decisiones de arquitectura; feedback inmediato y reintentos registrados en el LMS.",
        "href": "Presentaciones/M6/sesion-15-desafio-final.html",
        "tags": ["evaluación automática", "grano", "DDL", "SQL", "pruebas", "variaciones", "feedback", "LMS"],
        "recursos": [
            {"txt": "🧪 Evaluador automático S15", "href": "evaluador-s15.html"},
            {"txt": "🧭 Tablero del desafío", "href": "capstone.html"},
            {"txt": "✅ Contrato de evaluación", "href": "Plantillas/proyecto-final/criterios.md"},
        ],
    })
    dump(path, course)


def update_plan(path: Path) -> None:
    plan = json.loads(path.read_text(encoding="utf-8"))
    plan.setdefault("principios", {})["diferenciacion_tecnica_sesiones"] = [11, 12, 13, 14]
    old = plan["sesiones"]["15"]
    dp900 = old.get("dp900", [])
    plan["sesiones"]["15"] = {
        "fecha": old.get("fecha", "2026-09-18"),
        "titulo": "Desafío final · evaluación automática",
        "duracion_util": old.get("duracion_util", 165),
        "modo": "evaluacion_automatica_guiada",
        "objetivo": "Demostrar transferencia con una solución que sobreviva pruebas de integridad, consultas sobre datos variables y decisiones de arquitectura dadas restricciones explícitas.",
        "evaluacion": {
            "modo": "automatica",
            "href": "evaluador-s15.html",
            "puntaje_total": 100,
            "reintentos": True,
            "registro_lms": True,
            "criterios": [
                {"titulo": "Grano y lectura de fuentes", "puntos": 20},
                {"titulo": "DDL e integridad", "puntos": 25},
                {"titulo": "SQL y validación", "puntos": 35},
                {"titulo": "Arquitectura y adaptabilidad", "puntos": 20},
            ],
        },
        "dp900": dp900,
        "solucion": {"modo": "automatica", "href": "evaluador-s15.html"},
    }
    dump(path, plan)


def patch_constants(path: Path) -> None:
    if not path.exists():
        return
    text = path.read_text(encoding="utf-8")
    text = text.replace("{11, 12, 13, 14, 15}", "{11, 12, 13, 14}")
    text = text.replace("S11, S12, S13, S14 y S15: capa de práctica técnica no persistente.", "S11, S12, S13 y S14: capa de práctica técnica no persistente.")
    path.write_text(text, encoding="utf-8")


def main() -> int:
    for rel in ["Presentaciones/M6/sesion-15-desafio-final.html", "revision/Presentaciones/M6/sesion-15-desafio-final.html"]:
        (ROOT / rel).write_text(PRESENTATION, encoding="utf-8")
    for rel in ["capstone.html", "revision/capstone.html"]:
        (ROOT / rel).write_text(CAPSTONE, encoding="utf-8")
    for rel in ["Plantillas/proyecto-final/criterios.md", "revision/Plantillas/proyecto-final/criterios.md"]:
        p = ROOT / rel
        if p.parent.exists(): p.write_text(CRITERIA, encoding="utf-8")
    for rel in ["Plantillas/proyecto-final/README.md", "revision/Plantillas/proyecto-final/README.md"]:
        p = ROOT / rel
        if p.parent.exists(): p.write_text(README, encoding="utf-8")
    for rel in ["tools/curso.json", "revision/tools/curso.json"]:
        update_course(ROOT / rel)
    for rel in ["assets/learning/learning-plan.json", "revision/assets/learning/learning-plan.json"]:
        update_plan(ROOT / rel)
    for rel in ["tools/integrar-experiencia.py", "revision/tools/integrar-experiencia.py", "tools/validar_curso.py", "revision/tools/validar_curso.py"]:
        patch_constants(ROOT / rel)
    print("S15 automática sincronizada: presentación, tablero, manifiestos y planes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
